# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b140d390cfb4675876a63a4cc03aab7"
name = "Combo Product"
application_url = "https://combo-products.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://combo-products.vercel.app"
subpath = "combo-builder"
prefix = "apps"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"


[access_scopes]
scopes = "write_products,read_products,read_orders,read_inventory"

[auth]
redirect_urls = [
  "https://combo-products.vercel.app/auth/callback",
  "https://combo-products.vercel.app/shopify/callback",
  "https://combo-products.vercel.app/api/auth/callback"
]
